### ISSUE TITLE
PYNQ-Z1 board support

### ISSUE THREAD

**Issue by davidbrochart** [malkadi/FGPU_iPython#2]
Hi @malkadi,

I understand that this project has been developed on a ZC706 board, does it mean it doesn't work on a PYNQ-Z1 board?
It doesn't seem so, because it hangs when executing `fgpu.download_kernel()`.

**Comment by malkadi** [comment]
The z020 on PYNQ-Z1 is about 1/4 as big as the z045 on the ZC706. You may try to compile the FGPU for the Z1 board. However, I think that the performance would hardly meet the ARM Cortex-A9.

**Comment by davidbrochart** [comment]
I see, thanks.

**Comment by beef9** [comment]
When I try to compile for a different architecture (arm) for PYNQ-Z1 board, there is a file named "benchmark.cl" which is missing from repo.

```
xilinx@pynq:~/jupyter_notebooks/FGPU_IPython/FGPU$ ./compile.sh
OpenCL file is needed!
```

**Comment by malkadi** [comment]
@beef9  you may use any .cl file FGPU_IPython/notebooks/OpenCL_code
